name = "docbuild"
defaultTargets = ["Wordpuzzle"]
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"
fixedToolchain = true

[leanOptions]
maxHeartbeats = 0

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.32.0"

[[require]]
name = "Wordpuzzle"
path = "../"
