name = "Wordpuzzle"
version = "0.1.0-dev"              # see also Wordpuzzle.Config.appVersion
defaultTargets = ["wordpuzzle"]
lintDriver = "batteries/runLinter"
testDriver = "wordpuzzle_test"

[[lean_lib]]
name = "Wordpuzzle"

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "wordpuzzle"
root = "Wordpuzzle"

[[lean_exe]]
name = "wordpuzzle_test"
root = "Test"

# [[require]]
# scope = "leanprover"
# name = "doc-gen4"
# rev = "v4.31.0"  # matches toolchain version

[[require]]
name = "batteries"
scope = "leanprover-community"

[[dependency]]
name = "cli"
src = { git = "https://github.com/leanprover/lean4-cli.git", rev = "baf3e62fbb3502305076ca077e004aea78157c63" }
