name = "Wordpuzzle"
version = "0.1.0-dev"              # see also Wordpuzzle.Config.appVersion
defaultTargets = ["Wordpuzzle"]
lintDriver = "batteries/runLinter"
testDriver = "wordpuzzle_test"

[[lean_lib]]
name = "Wordpuzzle"
globs = ["Wordpuzzle", "Wordpuzzle.+"]


[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "wordpuzzle"
root = "Wordpuzzle"

[[lean_exe]]
name = "wordpuzzle_test"
root = "Test"

[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "cli"
git = "https://github.com/leanprover/lean4-cli.git"
rev = "baf3e62fbb3502305076ca077e004aea78157c63"
