---
name: lean-action-ci

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build, test and lint the project
        id: build-lean
        uses: leanprover/lean-action@v1

      - name: Run executable smoke-tests
        run: |
          lake exe wordpuzzle -h
          lake exe wordpuzzle -s 4 -m c -l cadevrsoi

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Re-build the project
        uses: leanprover/lean-action@v1
        with:
          test: false
          lint: false

      - name: Build documentation
        uses: leanprover-community/docgen-action@main
        continue-on-error: true
